{
 "title": "Livro",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "label": "application", "query": { "query": "label_values(application)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{application=\"$application\"}, instance)"
    }
   },
   {
    "name": "pool",
    "label": "pool",
    "query": {
     "query": "label_values(hikaricp_connections{instance=\"$instance\", application=\"$application\"}, pool)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Autores Count",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{application=\"app-livro-api\",exception=\"None\",method=\"GET\",uri=\"/v1/api/autores\",}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_count{application=\"app-livro-api\",exception=\"None\",method=\"POST\",uri=\"/v1/api/autores\",}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_count{application=\"app-livro-api\",exception=\"None\",method=\"GET\",uri=\"/v1/api/autores/{id}\",}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_count{application=\"app-livro-api\",exception=\"None\",method=\"PUT\",uri=\"/v1/api/autores/{id}\",}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_count{application=\"app-livro-api\",exception=\"None\",method=\"DELETE\",uri=\"/v1/api/autores/{id}\",}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    }
   ]
  },
  {
   "title": "Categoria Count",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 9, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{application=\"app-livro-api\", method=\"POST\", uri=\"/v1/api/categorias\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_count{application=\"app-livro-api\",method=\"GET\", uri=\"/v1/api/categorias/{id}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_count{application=\"app-livro-api\",method=\"GET\" ,uri=\"/v1/api/categorias\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_count{application=\"app-livro-api\",method=\"PUT\",uri=\"/v1/api/categorias/{id}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_count{application=\"app-livro-api\",method=\"DELETE\",uri=\"/v1/api/categorias/{id}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    }
   ]
  },
  {
   "title": "Livros Count",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{application=\"app-livro-api\",method=\"GET\",uri=\"/v1/api/livros\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_count{application=\"app-livro-api\",method=\"POST\",uri=\"/v1/api/livros\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_count{application=\"app-livro-api\",method=\"GET\",uri=\"/v1/api/livros/{id}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_count{application=\"app-livro-api\",method=\"PUT\",uri=\"/v1/api/livros/{id}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_count{application=\"app-livro-api\",method=\"DELETE\",uri=\"/v1/api/livros/{id}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    }
   ]
  },
  {
   "title": "Autores Sum",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_sum{application=\"app-livro-api\",method=\"POST\",uri=\"/v1/api/autores\",}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_sum{application=\"app-livro-api\",method=\"GET\",uri=\"/v1/api/autores\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_sum{application=\"app-livro-api\",method=\"GET\",uri=\"/v1/api/autores/{id}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_sum{application=\"app-livro-api\",method=\"PUT\",uri=\"/v1/api/autores/{id}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_sum{application=\"app-livro-api\",method=\"PUT\",uri=\"/v1/api/autores/{id}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    }
   ]
  },
  {
   "title": "Categoria Sum",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_sum{application=\"app-livro-api\", method=\"POST\", uri=\"/v1/api/categorias\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_sum{application=\"app-livro-api\",method=\"GET\", uri=\"/v1/api/categorias/{id}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_sum{application=\"app-livro-api\",method=\"GET\" ,uri=\"/v1/api/categorias\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_sum{application=\"app-livro-api\",method=\"PUT\",uri=\"/v1/api/categorias/{id}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_sum{application=\"app-livro-api\",method=\"DELETE\",uri=\"/v1/api/categorias/{id}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    }
   ]
  },
  {
   "title": "Livros Sum",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_sum{application=\"app-livro-api\", method=\"POST\",uri=\"/v1/api/livros\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_sum{application=\"app-livro-api\", method=\"GET\",uri=\"/v1/api/livros\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_sum{application=\"app-livro-api\", method=\"GET\",uri=\"/v1/api/livros/{id}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_sum{application=\"app-livro-api\", method=\"PUT\",uri=\"/v1/api/livros/{id}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_sum{application=\"app-livro-api\", method=\"DELETE\",uri=\"/v1/api/livros/{id}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    }
   ]
  },
  {
   "title": "Autores Max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{application=\"app-livro-api\",method=\"GET\",uri=\"/v1/api/autores\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_max{application=\"app-livro-api\",method=\"POST\",uri=\"/v1/api/autores\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_count{application=\"app-livro-api\",method=\"GET\",uri=\"/v1/api/autores/{id}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_max{application=\"app-livro-api\",method=\"PUT\",uri=\"/v1/api/autores/{id}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_max{application=\"app-livro-api\",method=\"DELETE\",uri=\"/v1/api/autores/{id}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    }
   ]
  },
  {
   "title": "Categoria Max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{application=\"app-livro-api\", method=\"POST\", uri=\"/v1/api/categorias\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_max{application=\"app-livro-api\",method=\"GET\", uri=\"/v1/api/categorias/{id}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_max{application=\"app-livro-api\",method=\"GET\" ,uri=\"/v1/api/categorias\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_max{application=\"app-livro-api\",method=\"PUT\",uri=\"/v1/api/categorias/{id}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_max{application=\"app-livro-api\",method=\"DELETE\",uri=\"/v1/api/categorias/{id}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    }
   ]
  },
  {
   "title": "Livros Max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{application=\"app-livro-api\", method=\"GET\",uri=\"/v1/api/livros\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_max{application=\"app-livro-api\", method=\"POST\",uri=\"/v1/api/livros\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_count{application=\"app-livro-api\", uri=\"/v1/api/livros/{id}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_max{application=\"app-livro-api\", method=\"PUT\",uri=\"/v1/api/livros/{id}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_max{application=\"app-livro-api\", method=\"DELETE\",uri=\"/v1/api/livros/{id}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    }
   ]
  }
 ]
}